[package]
license.workspace = true
name = "kura-config"
edition.workspace = true
version.workspace = true
rust-version.workspace = true

[dependencies]
kura-egress.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true

[dev-dependencies]
parking_lot.workspace = true
